const test = require('node:test');
const assert = require('node:assert/strict');
const { gridFsIdFromUrl, gridFsPublicUrl } = require('../src/services/gridFsMediaStorage.service');

test('GridFS media URLs round-trip without loading mongoose', () => {
  const id = '507f1f77bcf86cd799439011';
  const url = gridFsPublicUrl(id, 'brand image.png');
  assert.equal(url, `/uploads/db/${id}/brand%20image.png`);
  assert.equal(gridFsIdFromUrl(url), id);
  assert.equal(gridFsIdFromUrl(`https://example.com${url}?v=1`), id);
  assert.equal(gridFsIdFromUrl('/uploads/ai/image.png'), '');
});

test('GridFS storage persists and reads generated bytes through the MongoDB bucket', async () => {
  const Module = require('node:module');
  const { Writable, Readable } = require('node:stream');
  const id = '507f1f77bcf86cd799439011';
  let stored = Buffer.alloc(0);
  let record = null;

  class FakeObjectId {
    constructor(value) { this.value = String(value); }
    toString() { return this.value; }
    static isValid(value) { return /^[a-f\d]{24}$/i.test(String(value || '')); }
  }

  const bucket = {
    openUploadStream(filename, options = {}) {
      const chunks = [];
      const stream = new Writable({
        write(chunk, _encoding, callback) { chunks.push(Buffer.from(chunk)); callback(); },
        final(callback) {
          stored = Buffer.concat(chunks);
          record = {
            _id: new FakeObjectId(id),
            filename,
            length: stored.length,
            contentType: options.contentType,
            metadata: options.metadata
          };
          callback();
        }
      });
      stream.id = new FakeObjectId(id);
      return stream;
    },
    find() { return { limit() { return this; }, async next() { return record; } }; },
    openDownloadStream(_id, options = {}) {
      const start = options.start || 0;
      const end = options.end === undefined ? stored.length : options.end;
      return Readable.from(stored.subarray(start, end));
    }
  };

  const fakeMongoose = {
    connection: { readyState: 1, db: {} },
    mongo: { GridFSBucket: function GridFSBucket() { return bucket; } },
    Types: { ObjectId: FakeObjectId }
  };

  const originalLoad = Module._load;
  Module._load = function patched(request, parent, isMain) {
    if (request === 'mongoose') return fakeMongoose;
    return originalLoad.call(this, request, parent, isMain);
  };

  try {
    const service = require('../src/services/gridFsMediaStorage.service');
    const saved = await service.saveBufferToGridFs({
      buffer: Buffer.from('durable-media'),
      filename: 'post.png',
      mimeType: 'image/png'
    });
    assert.equal(saved.fileUrl, `/uploads/db/${id}/post.png`);
    assert.equal(await service.gridFsFileExists(saved.fileUrl), true);
    const downloaded = await service.readGridFsBuffer(saved.fileUrl);
    assert.equal(downloaded.buffer.toString(), 'durable-media');
    assert.equal(downloaded.contentType, 'image/png');
  } finally {
    Module._load = originalLoad;
  }
});
