const DEFAULT_PLAN_MATRIX = [
  {
    name: 'Free Trial',
    slug: 'free-trial',
    description: 'Try the core social media workflow for seven days.',
    price: 0,
    currency: 'USD',
    billingInterval: 'trial',
    trialDays: 7,
    sortOrder: 10,
    isPopular: false,
    queuePriority: 1,
    limits: {
      maxBrands: 1,
      maxSocialAccounts: 1,
      maxTeamMembers: 0,
      maxScheduledPosts: 10,
      maxAiTextGenerations: 25,
      maxAiImageGenerations: 5,
      maxAiVideoGenerations: 0,
      maxAvatarVideos: 0,
      maxHandoffPosts: 5,
      maxAutoPosts: 0,
      maxClientApprovalLinks: 0,
      maxStorageMb: 250
    },
    features: {
      brandBrainLevel: 'basic',
      smartComposerLevel: 'basic',
      analyticsLevel: 'basic',
      calendarAccess: true,
      handoffModeAccess: true,
      autoModeAccess: false,
      approvalWorkflowAccess: false
    },
    featureList: ['Basic Brand Brain', 'Basic Smart Composer', 'Basic Calendar', 'Limited Handoff', 'Low queue priority'],
    aiConfig: {
      allowedProviders: ['local', 'openai'],
      allowedModels: ['local-fast'],
      defaultTextProvider: 'local',
      defaultTextModel: 'local-fast',
      defaultImageProvider: 'local',
      defaultImageModel: 'local-image',
      fallbackProvider: 'local',
      fallbackModel: 'local-fallback',
      monthlyTokenLimit: 25000,
      monthlyImageLimit: 5,
      monthlyVideoLimit: 0,
      allowUserProviderSelection: false
    }
  },
  {
    name: 'Starter',
    slug: 'starter',
    description: 'For solo brands that need consistent scheduled content.',
    price: 10,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 20,
    isPopular: false,
    queuePriority: 3,
    limits: {
      maxBrands: 1,
      maxSocialAccounts: 3,
      maxTeamMembers: 1,
      maxScheduledPosts: 50,
      maxAiTextGenerations: 300,
      maxAiImageGenerations: 30,
      maxAiVideoGenerations: 0,
      maxAvatarVideos: 0,
      maxHandoffPosts: 25,
      maxAutoPosts: 0,
      maxClientApprovalLinks: 0,
      maxStorageMb: 1000
    },
    features: { brandBrainLevel: 'basic', smartComposerLevel: 'standard', analyticsLevel: 'basic', handoffModeAccess: true },
    featureList: ['Smart Composer', 'Calendar', 'Basic Analytics', 'Handoff Mode', 'Normal queue priority'],
    aiConfig: {
      allowedProviders: ['local', 'openai', 'gemini'],
      allowedModels: ['local-fast', 'gpt-4.1-mini', 'gemini-2.5-flash'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1-mini',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      fallbackProvider: 'local',
      fallbackModel: 'local-fallback',
      monthlyTokenLimit: 300000,
      monthlyImageLimit: 30,
      monthlyVideoLimit: 0,
      allowUserProviderSelection: false
    }
  },
  {
    name: 'Growth',
    slug: 'growth',
    description: 'For growing teams using campaigns, approvals and limited Auto Mode.',
    price: 20,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 30,
    isPopular: true,
    queuePriority: 5,
    limits: {
      maxBrands: 3,
      maxSocialAccounts: 10,
      maxTeamMembers: 3,
      maxScheduledPosts: 200,
      maxAiTextGenerations: 1000,
      maxAiImageGenerations: 100,
      maxAiVideoGenerations: 5,
      maxAvatarVideos: 0,
      maxHandoffPosts: 100,
      maxAutoPosts: 50,
      maxClientApprovalLinks: 50,
      maxStorageMb: 5000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'standard',
      campaignAccess: true,
      growthStudioAccess: true,
      contentRepurposingAccess: true,
      autoModeAccess: true,
      approvalWorkflowAccess: true,
      handoffModeAccess: true
    },
    featureList: ['Advanced Brand Brain', 'Campaigns', 'Growth Studio', 'Approval links', 'Limited Auto Mode'],
    aiConfig: {
      allowedProviders: ['local', 'openai', 'gemini', 'deepseek', 'groq'],
      allowedModels: ['gpt-4.1-mini', 'gemini-2.5-flash', 'deepseek-chat', 'llama-3.3-70b-versatile'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1-mini',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'replicate',
      defaultVideoModel: 'default-video',
      fallbackProvider: 'local',
      fallbackModel: 'local-fallback',
      monthlyTokenLimit: 1000000,
      monthlyImageLimit: 100,
      monthlyVideoLimit: 5,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Pro',
    slug: 'pro',
    description: 'For serious content operations with scoring, bulk create and video.',
    price: 50,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 40,
    isPopular: false,
    queuePriority: 7,
    limits: {
      maxBrands: 10,
      maxSocialAccounts: 30,
      maxTeamMembers: 10,
      maxScheduledPosts: 1000,
      maxAiTextGenerations: 5000,
      maxAiImageGenerations: 500,
      maxAiVideoGenerations: 25,
      maxAvatarVideos: 5,
      maxHandoffPosts: 500,
      maxAutoPosts: 300,
      maxClientApprovalLinks: 500,
      maxStorageMb: 25000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'advanced',
      contentScoreAccess: true,
      brandFitCheckerAccess: true,
      riskCheckerAccess: true,
      bestTimeSuggestionAccess: true,
      bulkCreateAccess: true,
      approvalWorkflowAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true
    },
    featureList: ['Content score', 'Brand fit checker', 'Best-time suggestions', 'Bulk create', 'Advanced analytics'],
    aiConfig: {
      allowedProviders: ['local', 'openai', 'gemini', 'deepseek', 'groq', 'anthropic', 'mistral', 'replicate', 'stability', 'fal'],
      allowedModels: ['gpt-4.1', 'gpt-4.1-mini', 'claude-3-5-sonnet-latest', 'gemini-2.5-pro', 'deepseek-chat', 'mistral-large-latest'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'replicate',
      defaultVideoModel: 'default-video',
      fallbackProvider: 'anthropic',
      fallbackModel: 'claude-3-5-haiku-latest',
      monthlyTokenLimit: 5000000,
      monthlyImageLimit: 500,
      monthlyVideoLimit: 25,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Business',
    slug: 'business',
    description: 'For larger teams with client portal, recovery and priority support.',
    price: 100,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 50,
    isPopular: false,
    queuePriority: 9,
    limits: {
      maxBrands: 30,
      maxSocialAccounts: 100,
      maxTeamMembers: 25,
      maxScheduledPosts: 5000,
      maxAiTextGenerations: 15000,
      maxAiImageGenerations: 1500,
      maxAiVideoGenerations: 100,
      maxAvatarVideos: 25,
      maxHandoffPosts: 2000,
      maxAutoPosts: 1500,
      maxClientApprovalLinks: 2000,
      maxStorageMb: 100000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'advanced',
      clientApprovalPortalAccess: true,
      competitorWatchAccess: true,
      failedPostRecoveryAccess: true,
      prioritySupportAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true,
      approvalWorkflowAccess: true
    },
    featureList: ['Client approval portal', 'Competitor watch', 'Failed post recovery', 'Priority support', 'Premium routing'],
    aiConfig: {
      allowedProviders: ['local', 'openai', 'gemini', 'deepseek', 'groq', 'anthropic', 'mistral', 'replicate', 'stability', 'fal'],
      allowedModels: ['gpt-4.1', 'claude-3-5-sonnet-latest', 'gemini-2.5-pro', 'deepseek-chat', 'mistral-large-latest'],
      defaultTextProvider: 'anthropic',
      defaultTextModel: 'claude-3-5-sonnet-latest',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'replicate',
      defaultVideoModel: 'default-video',
      fallbackProvider: 'openai',
      fallbackModel: 'gpt-4.1-mini',
      monthlyTokenLimit: 15000000,
      monthlyImageLimit: 1500,
      monthlyVideoLimit: 100,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Agency',
    slug: 'agency',
    description: 'For agencies with white label, portals and highest queue priority.',
    price: 150,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 60,
    isPopular: false,
    queuePriority: 10,
    limits: {
      maxBrands: 100,
      maxSocialAccounts: 300,
      maxTeamMembers: 100,
      maxScheduledPosts: 20000,
      maxAiTextGenerations: 50000,
      maxAiImageGenerations: 5000,
      maxAiVideoGenerations: 300,
      maxAvatarVideos: 100,
      maxHandoffPosts: 10000,
      maxAutoPosts: 7500,
      maxClientApprovalLinks: 10000,
      maxStorageMb: 500000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'advanced',
      whiteLabelAccess: true,
      clientApprovalPortalAccess: true,
      agencyWorkspaceAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true,
      approvalWorkflowAccess: true,
      contentRepurposingAccess: true,
      bulkCreateAccess: true
    },
    featureList: ['White label', 'Client portals', 'Agency workspace', 'Advanced AI routing', 'Highest queue priority'],
    aiConfig: {
      allowedProviders: ['local', 'openai', 'gemini', 'deepseek', 'groq', 'anthropic', 'mistral', 'replicate', 'stability', 'fal'],
      allowedModels: ['*'],
      defaultTextProvider: 'anthropic',
      defaultTextModel: 'claude-3-5-sonnet-latest',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'fal',
      defaultVideoModel: 'default-video',
      fallbackProvider: 'openai',
      fallbackModel: 'gpt-4.1-mini',
      monthlyTokenLimit: 50000000,
      monthlyImageLimit: 5000,
      monthlyVideoLimit: 300,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Superadmin',
    slug: 'superadmin',
    description: 'Internal unlimited platform administrator plan.',
    price: 0,
    currency: 'USD',
    billingInterval: 'manual',
    trialDays: 0,
    sortOrder: 999,
    isPopular: false,
    isPublic: false,
    queuePriority: 100,
    limits: {
      maxBrands: -1,
      maxSocialAccounts: -1,
      maxTeamMembers: -1,
      maxScheduledPosts: -1,
      maxAiTextGenerations: -1,
      maxAiImageGenerations: -1,
      maxAiVideoGenerations: -1,
      maxAvatarVideos: -1,
      maxHandoffPosts: -1,
      maxAutoPosts: -1,
      maxClientApprovalLinks: -1,
      maxStorageMb: -1
    },
    features: {
      brandBrainLevel: 'unlimited',
      smartComposerLevel: 'unlimited',
      analyticsLevel: 'unlimited',
      calendarAccess: true,
      campaignAccess: true,
      growthStudioAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true,
      approvalWorkflowAccess: true,
      clientApprovalPortalAccess: true,
      contentRepurposingAccess: true,
      bulkCreateAccess: true,
      contentScoreAccess: true,
      brandFitCheckerAccess: true,
      riskCheckerAccess: true,
      bestTimeSuggestionAccess: true,
      competitorWatchAccess: true,
      whiteLabelAccess: true,
      prioritySupportAccess: true,
      templateAccess: true,
      failedPostRecoveryAccess: true,
      agencyWorkspaceAccess: true
    },
    featureList: ['Unlimited everything', 'All providers', 'All models', 'All admin settings'],
    aiConfig: {
      allowedProviders: ['*'],
      allowedModels: ['*'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1',
      fallbackProvider: 'anthropic',
      fallbackModel: 'claude-3-5-sonnet-latest',
      monthlyTokenLimit: -1,
      monthlyImageLimit: -1,
      monthlyVideoLimit: -1,
      allowUserProviderSelection: true
    }
  }
];

module.exports = { DEFAULT_PLAN_MATRIX };
