const DEFAULT_PLAN_MATRIX = [
  {
    name: 'Free Trial',
    slug: 'free-trial',
    description: 'Try the real AutoBrand workflow for seven days with no payment and no automatic paid conversion.',
    price: 0,
    currency: 'USD',
    billingInterval: 'trial',
    trialDays: 7,
    sortOrder: 10,
    isPopular: false,
    queuePriority: 1,
    includedCredits: 350,
    limits: {
      maxBrands: 1,
      maxSocialAccounts: 1,
      maxTeamMembers: 0,
      maxScheduledPosts: 10,

      maxManualPosts: 250,
      maxAiTextGenerations: 25,
      maxAiImageGenerations: 5,
      maxAiVideoGenerations: 0,
      maxAvatarVideos: 0,
      maxHandoffPosts: 5,
      maxAutoPosts: 0,
      maxClientApprovalLinks: 0,
      maxStorageMb: 250
    },
    features: {
      brandBrainLevel: 'basic',
      smartComposerLevel: 'basic',
      analyticsLevel: 'basic',
      manualPublisherAccess: true,
      calendarAccess: true,
      handoffModeAccess: true,
      autoModeAccess: false,
      approvalWorkflowAccess: false
    },
    featureList: ['Basic Brand Brain Assist', 'Basic Smart Composer', 'Basic Calendar', 'Limited AI-assisted Handoff', 'ChatGPT + Drive connection', 'Low queue priority'],
    aiConfig: {
      allowedProviders: ['openai'],
      allowedModels: ['gpt-4.1-mini', 'gpt-image-1'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1-mini',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      fallbackProvider: '',
      fallbackModel: '',
      monthlyTokenLimit: 25000,
      monthlyImageLimit: 5,
      monthlyVideoLimit: 0,
      allowUserProviderSelection: false
    }
  },
  {
    name: 'Publish',
    slug: 'manual-publisher',
    description: 'Affordable publishing infrastructure with ChatGPT connectivity, Google Drive assets, scheduling, approvals and analytics for teams that bring their own creative work.',
    price: 10,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 15,
    isPopular: false,
    queuePriority: 4,
    includedCredits: 0,
    limits: {
      maxBrands: 2,
      maxSocialAccounts: 6,
      maxTeamMembers: 2,
      maxScheduledPosts: 300,
      maxManualPosts: 1000,
      maxAiTextGenerations: 0,
      maxAiImageGenerations: 0,
      maxAiVideoGenerations: 0,
      maxAvatarVideos: 0,
      maxHandoffPosts: 100,
      maxAutoPosts: 0,
      maxClientApprovalLinks: 50,
      maxStorageMb: 5000
    },
    features: {
      brandBrainLevel: 'basic',
      smartComposerLevel: 'none',
      analyticsLevel: 'standard',
      manualPublisherAccess: true,
      calendarAccess: true,
      handoffModeAccess: true,
      approvalWorkflowAccess: true,
      bulkImportAccess: true,
      templateAccess: true,
      contentScoreAccess: true,
      brandFitCheckerAccess: true,
      riskCheckerAccess: true,
      bestTimeSuggestionAccess: true,
      failedPostRecoveryAccess: true,
      campaignAccess: false,
      growthStudioAccess: false,
      autoModeAccess: false
    },
    featureList: [
      'No AI usage or AI generation cost',
      'Bring your own ads and captions',
      'Upload images and videos',
      'Combine text and media into platform-ready posts',
      'Publish now or schedule across connected accounts',
      'Deterministic platform formatting and validation',
      'Local template-video rendering with zero AI credits',
      'Content score, brand-fit and risk checks without generative AI',
      'Calendar, analytics, recovery and approval workflow',
      '5 GB media storage'
    ],
    aiConfig: {
      allowedProviders: [],
      allowedModels: [],
      defaultTextProvider: '',
      defaultTextModel: '',
      defaultImageProvider: '',
      defaultImageModel: '',
      defaultVideoProvider: '',
      defaultVideoModel: '',
      fallbackProvider: '',
      fallbackModel: '',
      monthlyTokenLimit: 0,
      monthlyImageLimit: 0,
      monthlyVideoLimit: 0,
      allowUserProviderSelection: false
    }
  },
  {
    name: 'AI Starter',
    slug: 'starter',
    description: 'AI-assisted publishing for solo brands that want captions, images and scheduling without advanced automation.',
    price: 10,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 20,
    isPopular: false,
    queuePriority: 3,
    includedCredits: 4000,
    limits: {
      maxBrands: 1,
      maxSocialAccounts: 3,
      maxTeamMembers: 1,
      maxScheduledPosts: 50,

      maxManualPosts: 250,
      maxAiTextGenerations: 300,
      maxAiImageGenerations: 30,
      maxAiVideoGenerations: 0,
      maxAvatarVideos: 0,
      maxHandoffPosts: 25,
      maxAutoPosts: 0,
      maxClientApprovalLinks: 0,
      maxStorageMb: 1000
    },
    features: {
      brandBrainLevel: 'basic',
      smartComposerLevel: 'standard',
      analyticsLevel: 'basic',
      manualPublisherAccess: true,
      calendarAccess: true,
      handoffModeAccess: true,
      templateAccess: true,
      autoModeAccess: false,
      approvalWorkflowAccess: false,
      campaignAccess: false,
      growthStudioAccess: false
    },
    featureList: ['AI Brain Assist', 'Smart Composer', 'AI captions and images', 'Calendar', 'Basic Analytics', 'AI-assisted Handoff', 'ChatGPT + Drive connection', 'Normal queue priority'],
    aiConfig: {
      allowedProviders: ['openai'],
      allowedModels: ['gpt-4.1-mini', 'gpt-image-1'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1-mini',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      fallbackProvider: '',
      fallbackModel: '',
      monthlyTokenLimit: 300000,
      monthlyImageLimit: 30,
      monthlyVideoLimit: 0,
      allowUserProviderSelection: false
    }
  },
  {
    name: 'Growth',
    slug: 'growth',
    description: 'AI campaigns, approvals, video and limited Auto Mode for growing teams.',
    price: 20,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 30,
    isPopular: true,
    queuePriority: 5,
    includedCredits: 14000,
    limits: {
      maxBrands: 3,
      maxSocialAccounts: 10,
      maxTeamMembers: 3,
      maxScheduledPosts: 200,

      maxManualPosts: 1000,
      maxAiTextGenerations: 1000,
      maxAiImageGenerations: 100,
      maxAiVideoGenerations: 5,
      maxAvatarVideos: 0,
      maxHandoffPosts: 100,
      maxAutoPosts: 50,
      maxClientApprovalLinks: 50,
      maxStorageMb: 5000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'standard',
      manualPublisherAccess: true,
      calendarAccess: true,
      campaignAccess: true,
      growthStudioAccess: true,
      contentRepurposingAccess: true,
      autoModeAccess: true,
      approvalWorkflowAccess: true,
      handoffModeAccess: true,
      templateAccess: true
    },
    featureList: ['Advanced AI Brain', 'Background approval mode', 'AI Brain Autopilot', 'Campaigns', 'Growth Studio', 'Approval links', 'Analytics learning'],
    aiConfig: {
      allowedProviders: ['openai'],
      allowedModels: ['gpt-4.1-mini', 'gpt-image-1', 'sora-2'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1-mini',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'openai',
      defaultVideoModel: 'sora-2',
      fallbackProvider: '',
      fallbackModel: '',
      monthlyTokenLimit: 1000000,
      monthlyImageLimit: 100,
      monthlyVideoLimit: 5,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Pro',
    slug: 'pro',
    description: 'Advanced AI, video, scoring, bulk creation and analytics for serious content operations.',
    price: 50,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 40,
    isPopular: false,
    queuePriority: 7,
    includedCredits: 70000,
    limits: {
      maxBrands: 10,
      maxSocialAccounts: 30,
      maxTeamMembers: 10,
      maxScheduledPosts: 1000,

      maxManualPosts: 5000,
      maxAiTextGenerations: 5000,
      maxAiImageGenerations: 500,
      maxAiVideoGenerations: 25,
      maxAvatarVideos: 5,
      maxHandoffPosts: 500,
      maxAutoPosts: 300,
      maxClientApprovalLinks: 500,
      maxStorageMb: 25000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'advanced',
      manualPublisherAccess: true,
      calendarAccess: true,
      campaignAccess: true,
      growthStudioAccess: true,
      contentRepurposingAccess: true,
      contentScoreAccess: true,
      brandFitCheckerAccess: true,
      riskCheckerAccess: true,
      bestTimeSuggestionAccess: true,
      bulkCreateAccess: true,
      approvalWorkflowAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true,
      templateAccess: true
    },
    featureList: ['Advanced AI Brain Autopilot', 'Content score', 'Brand fit checker', 'Best-time suggestions', 'Bulk create', 'Advanced analytics'],
    aiConfig: {
      allowedProviders: ['openai'],
      allowedModels: ['gpt-4.1', 'gpt-4.1-mini', 'gpt-image-1', 'sora-2'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'openai',
      defaultVideoModel: 'sora-2',
      fallbackProvider: 'openai',
      fallbackModel: 'gpt-4.1-mini',
      monthlyTokenLimit: 5000000,
      monthlyImageLimit: 500,
      monthlyVideoLimit: 25,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Business',
    slug: 'business',
    description: 'Large-team AI operations with client workflows, recovery and priority support.',
    price: 100,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 50,
    isPopular: false,
    queuePriority: 9,
    includedCredits: 210000,
    limits: {
      maxBrands: 30,
      maxSocialAccounts: 100,
      maxTeamMembers: 25,
      maxScheduledPosts: 5000,

      maxManualPosts: 25000,
      maxAiTextGenerations: 15000,
      maxAiImageGenerations: 1500,
      maxAiVideoGenerations: 100,
      maxAvatarVideos: 25,
      maxHandoffPosts: 2000,
      maxAutoPosts: 1500,
      maxClientApprovalLinks: 2000,
      maxStorageMb: 100000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'advanced',
      manualPublisherAccess: true,
      calendarAccess: true,
      campaignAccess: true,
      growthStudioAccess: true,
      contentRepurposingAccess: true,
      contentScoreAccess: true,
      brandFitCheckerAccess: true,
      riskCheckerAccess: true,
      bestTimeSuggestionAccess: true,
      bulkCreateAccess: true,
      clientApprovalPortalAccess: true,
      competitorWatchAccess: true,
      failedPostRecoveryAccess: true,
      prioritySupportAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true,
      approvalWorkflowAccess: true,
      templateAccess: true
    },
    featureList: ['Large-team AI Brain automation', 'Client approval portal', 'Competitor watch', 'Failed post recovery', 'Priority support', 'Premium routing'],
    aiConfig: {
      allowedProviders: ['openai'],
      allowedModels: ['gpt-4.1', 'gpt-4.1-mini', 'gpt-image-1', 'sora-2'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'openai',
      defaultVideoModel: 'sora-2',
      fallbackProvider: 'openai',
      fallbackModel: 'gpt-4.1-mini',
      monthlyTokenLimit: 15000000,
      monthlyImageLimit: 1500,
      monthlyVideoLimit: 100,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Agency',
    slug: 'agency',
    description: 'Multi-client agency operations with white label, portals and the highest queue priority.',
    price: 150,
    currency: 'USD',
    billingInterval: 'month',
    trialDays: 0,
    sortOrder: 60,
    isPopular: false,
    queuePriority: 10,
    includedCredits: 700000,
    limits: {
      maxBrands: 100,
      maxSocialAccounts: 300,
      maxTeamMembers: 100,
      maxScheduledPosts: 20000,

      maxManualPosts: 100000,
      maxAiTextGenerations: 50000,
      maxAiImageGenerations: 5000,
      maxAiVideoGenerations: 300,
      maxAvatarVideos: 100,
      maxHandoffPosts: 10000,
      maxAutoPosts: 7500,
      maxClientApprovalLinks: 10000,
      maxStorageMb: 500000
    },
    features: {
      brandBrainLevel: 'advanced',
      smartComposerLevel: 'advanced',
      analyticsLevel: 'advanced',
      manualPublisherAccess: true,
      calendarAccess: true,
      campaignAccess: true,
      growthStudioAccess: true,
      contentRepurposingAccess: true,
      contentScoreAccess: true,
      brandFitCheckerAccess: true,
      riskCheckerAccess: true,
      bestTimeSuggestionAccess: true,
      bulkCreateAccess: true,
      clientApprovalPortalAccess: true,
      competitorWatchAccess: true,
      failedPostRecoveryAccess: true,
      prioritySupportAccess: true,
      whiteLabelAccess: true,
      agencyWorkspaceAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true,
      approvalWorkflowAccess: true,
      templateAccess: true
    },
    featureList: ['Multi-client AI Brain automation', 'White label', 'Client portals', 'Agency workspace', 'Priority AI access', 'Highest queue priority'],
    aiConfig: {
      allowedProviders: ['openai'],
      allowedModels: ['*'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1',
      defaultImageProvider: 'openai',
      defaultImageModel: 'gpt-image-1',
      defaultVideoProvider: 'openai',
      defaultVideoModel: 'sora-2',
      fallbackProvider: 'openai',
      fallbackModel: 'gpt-4.1-mini',
      monthlyTokenLimit: 50000000,
      monthlyImageLimit: 5000,
      monthlyVideoLimit: 300,
      allowUserProviderSelection: true
    }
  },
  {
    name: 'Superadmin',
    slug: 'superadmin',
    description: 'Internal unlimited platform administrator plan.',
    price: 0,
    currency: 'USD',
    billingInterval: 'one_time',
    trialDays: 0,
    sortOrder: 999,
    isPopular: false,
    isPublic: false,
    queuePriority: 100,
    includedCredits: -1,
    limits: {
      maxBrands: -1,
      maxSocialAccounts: -1,
      maxTeamMembers: -1,
      maxScheduledPosts: -1,

      maxManualPosts: -1,
      maxAiTextGenerations: -1,
      maxAiImageGenerations: -1,
      maxAiVideoGenerations: -1,
      maxAvatarVideos: -1,
      maxHandoffPosts: -1,
      maxAutoPosts: -1,
      maxClientApprovalLinks: -1,
      maxStorageMb: -1
    },
    features: {
      brandBrainLevel: 'unlimited',
      smartComposerLevel: 'unlimited',
      analyticsLevel: 'unlimited',
      manualPublisherAccess: true,
      calendarAccess: true,
      campaignAccess: true,
      growthStudioAccess: true,
      autoModeAccess: true,
      handoffModeAccess: true,
      approvalWorkflowAccess: true,
      clientApprovalPortalAccess: true,
      contentRepurposingAccess: true,
      bulkCreateAccess: true,
      contentScoreAccess: true,
      brandFitCheckerAccess: true,
      riskCheckerAccess: true,
      bestTimeSuggestionAccess: true,
      competitorWatchAccess: true,
      whiteLabelAccess: true,
      prioritySupportAccess: true,
      templateAccess: true,
      failedPostRecoveryAccess: true,
      agencyWorkspaceAccess: true
    },
    featureList: ['Unlimited everything', 'All models', 'All admin settings'],
    aiConfig: {
      allowedProviders: ['*'],
      allowedModels: ['*'],
      defaultTextProvider: 'openai',
      defaultTextModel: 'gpt-4.1',
      fallbackProvider: 'openai',
      fallbackModel: 'gpt-4.1-mini',
      monthlyTokenLimit: -1,
      monthlyImageLimit: -1,
      monthlyVideoLimit: -1,
      allowUserProviderSelection: true
    }
  }
];

// Core operator/storage/workspace integrations are explicit entitlements.
// They are intentionally available on every current public plan because they do
// not bypass the plan matrix: ChatGPT inherits the user's AutoBrand permissions
// and quotas, Drive uses the user's own storage, and channel workspaces render
// only the analytics/features allowed by the active plan. Keeping this map
// explicit prevents a future plan from being silently unlocked by a blanket
// default.
const CORE_INTEGRATION_ENTITLEMENTS = Object.freeze({
  'free-trial': { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true },
  'manual-publisher': { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true },
  starter: { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true },
  growth: { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true },
  pro: { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true },
  business: { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true },
  agency: { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true },
  superadmin: { chatgptConnectorAccess: true, googleDriveAccess: true, channelWorkspacesAccess: true }
});

for (const plan of DEFAULT_PLAN_MATRIX) {
  const integrationEntitlements = CORE_INTEGRATION_ENTITLEMENTS[plan.slug] || {};
  plan.features = {
    ...integrationEntitlements,
    ...(plan.features || {})
  };
}

const publishPlan = DEFAULT_PLAN_MATRIX.find((plan) => plan.slug === 'manual-publisher');
if (publishPlan) {
  publishPlan.featureList = [
    'Connect ChatGPT/Codex to create, organize, schedule and publish',
    'Google Drive asset library or AutoBrand storage — your choice',
    'Bring your own captions, images and videos with zero AutoBrand AI-generation cost',
    'Publish now or schedule across connected accounts',
    'Per-channel workspaces with post performance and analytics',
    'Approvals, calendar, recovery, templates and deterministic platform formatting',
    '5 GB AutoBrand media storage plus optional Drive-backed assets'
  ];
}

module.exports = { DEFAULT_PLAN_MATRIX };
