try { require('dotenv').config(); } catch (error) { /* dotenv is optional in test/runtime bundles */ }

function cleanEnv(value) {
  return String(value || '').trim();
}

const env = {
  appName: process.env.APP_NAME || 'AutoBrand AI',
  appUrl: process.env.APP_URL || `http://localhost:${process.env.PORT || 3200}`,
  port: Number(process.env.PORT || 3200),
  nodeEnv: process.env.NODE_ENV || 'development',
  mongoUri: process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/ai-autobrand',
  aiTextProvider: process.env.AI_TEXT_PROVIDER || 'openai',
  aiImageProvider: process.env.AI_IMAGE_PROVIDER || 'openai',
  aiVideoProvider: process.env.AI_VIDEO_PROVIDER || 'openai',
  publicAppUrl: process.env.PUBLIC_APP_URL || process.env.APP_URL || '',

  superadminName: cleanEnv(process.env.SUPERADMIN_NAME) || 'Super Admin',
  superadminEmail: cleanEnv(process.env.SUPERADMIN_EMAIL) || 'admin@example.com',
  superadminPassword: cleanEnv(process.env.SUPERADMIN_PASSWORD) || 'ChangeMe123!',
  billingProvider: cleanEnv(process.env.BILLING_PROVIDER) || 'pesapal',
  checkoutDefaultProvider: cleanEnv(process.env.CHECKOUT_DEFAULT_PROVIDER) || cleanEnv(process.env.BILLING_PROVIDER) || 'pesapal',
  pesapalEnvironment: cleanEnv(process.env.PESAPAL_ENVIRONMENT || process.env.PESAPAL_MODE) || 'sandbox',
  pesapalBaseUrl: cleanEnv(process.env.PESAPAL_BASE_URL),
  pesapalConsumerKey: cleanEnv(process.env.PESAPAL_CONSUMER_KEY),
  pesapalConsumerSecret: cleanEnv(process.env.PESAPAL_CONSUMER_SECRET),
  pesapalIpnId: cleanEnv(process.env.PESAPAL_IPN_ID || process.env.PESAPAL_NOTIFICATION_ID),
  pesapalIpnUrl: cleanEnv(process.env.PESAPAL_IPN_URL),
  pesapalCallbackUrl: cleanEnv(process.env.PESAPAL_CALLBACK_URL),
  pesapalCancellationUrl: cleanEnv(process.env.PESAPAL_CANCELLATION_URL),
  pesapalRedirectMode: cleanEnv(process.env.PESAPAL_REDIRECT_MODE) || 'TOP_WINDOW',
  pesapalIpnNotificationType: cleanEnv(process.env.PESAPAL_IPN_NOTIFICATION_TYPE) || 'POST',
  pesapalAutoRegisterIpn: String(process.env.PESAPAL_AUTO_REGISTER_IPN || '').toLowerCase() === 'true',
  pesapalBranch: cleanEnv(process.env.PESAPAL_BRANCH) || '',
  pesapalTimeoutMs: Number(process.env.PESAPAL_TIMEOUT_MS || 30000),
  deepseekApiKey: cleanEnv(process.env.DEEPSEEK_API_KEY),
  deepseekTextModel: cleanEnv(process.env.DEEPSEEK_TEXT_MODEL) || 'deepseek-chat',
  groqApiKey: cleanEnv(process.env.GROQ_API_KEY),
  groqTextModel: cleanEnv(process.env.GROQ_TEXT_MODEL) || 'llama-3.3-70b-versatile',
  anthropicApiKey: cleanEnv(process.env.ANTHROPIC_API_KEY),
  anthropicTextModel: cleanEnv(process.env.ANTHROPIC_TEXT_MODEL) || 'claude-3-5-sonnet-latest',
  mistralApiKey: cleanEnv(process.env.MISTRAL_API_KEY),
  mistralTextModel: cleanEnv(process.env.MISTRAL_TEXT_MODEL) || 'mistral-large-latest',
  stabilityApiKey: cleanEnv(process.env.STABILITY_API_KEY),
  stabilityImageModel: cleanEnv(process.env.STABILITY_IMAGE_MODEL) || 'stable-image-core',
  falApiKey: cleanEnv(process.env.FAL_API_KEY),
  falImageModel: cleanEnv(process.env.FAL_IMAGE_MODEL) || 'fal-ai/flux/schnell',
  falVideoModel: cleanEnv(process.env.FAL_VIDEO_MODEL) || 'fal-ai/video',
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  geminiTextModel: process.env.GEMINI_TEXT_MODEL || 'gemini-2.5-flash',
  geminiImageModel: process.env.GEMINI_IMAGE_MODEL || 'gemini-2.5-flash-image-preview',
  replicateApiToken: process.env.REPLICATE_API_TOKEN || '',
  replicateImageModel: process.env.REPLICATE_IMAGE_MODEL || 'black-forest-labs/flux-schnell',
  replicateVideoModel: process.env.REPLICATE_VIDEO_MODEL || 'alibaba/happyhorse-1.0',
  openaiApiKey: process.env.OPENAI_API_KEY || '',
  openaiModel: process.env.OPENAI_MODEL || 'gpt-4.1-mini',
  openaiImageModel: process.env.OPENAI_IMAGE_MODEL || 'gpt-image-1',
  openaiImageSize: process.env.OPENAI_IMAGE_SIZE || '1024x1024',
  openaiQuality: process.env.OPENAI_QUALITY || 'medium',
  openaiVideoModel: process.env.OPENAI_VIDEO_MODEL || 'sora-2',
  openaiVideoSize: process.env.OPENAI_VIDEO_SIZE || '',
  openaiVideoSeconds: process.env.OPENAI_VIDEO_SECONDS || '',
  allowLocalImageFallback: String(process.env.ALLOW_LOCAL_IMAGE_FALLBACK || '').toLowerCase() === 'true',
  imageMagickBinary: process.env.IMAGE_MAGICK_BINARY || '',
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME || '',
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY || '',
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET || '',
  googleClientId: cleanEnv(process.env.GOOGLE_CLIENT_ID),
  googleClientSecret: cleanEnv(process.env.GOOGLE_CLIENT_SECRET),
  googleCallbackUrl: cleanEnv(process.env.GOOGLE_CALLBACK_URL) || `${process.env.APP_URL || 'http://localhost:3200'}/auth/google/callback`,
  googleOAuthTimeoutMs: Number(process.env.GOOGLE_OAUTH_TIMEOUT_MS || 30000),
  googleOAuthConnectTimeoutMs: Number(process.env.GOOGLE_OAUTH_CONNECT_TIMEOUT_MS || process.env.GOOGLE_OAUTH_TIMEOUT_MS || 30000),
  googleOAuthProxy: cleanEnv(process.env.GOOGLE_OAUTH_PROXY || process.env.HTTPS_PROXY || process.env.HTTP_PROXY),
  googleOAuthDnsOrder: cleanEnv(process.env.GOOGLE_OAUTH_DNS_ORDER),
  googleOAuthIpFamily: cleanEnv(process.env.GOOGLE_OAUTH_IP_FAMILY),
  googleBusinessClientId: cleanEnv(process.env.GOOGLE_BUSINESS_CLIENT_ID || process.env.GOOGLE_CLIENT_ID),
  googleBusinessClientSecret: cleanEnv(process.env.GOOGLE_BUSINESS_CLIENT_SECRET || process.env.GOOGLE_CLIENT_SECRET),
  googleBusinessCallbackUrl: cleanEnv(process.env.GOOGLE_BUSINESS_CALLBACK_URL) || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/google-business/callback`,
  googleBusinessScopes: process.env.GOOGLE_BUSINESS_SCOPES || 'https://www.googleapis.com/auth/business.manage',
  linkedinClientId: process.env.LINKEDIN_CLIENT_ID || '',
  linkedinClientSecret: process.env.LINKEDIN_CLIENT_SECRET || '',
  linkedinCallbackUrl: process.env.LINKEDIN_CALLBACK_URL || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/linkedin/callback`,
  linkedinScopes: process.env.LINKEDIN_SCOPES || 'openid profile email w_member_social',
  linkedinVersion: process.env.LINKEDIN_VERSION || '202605',
  pinterestClientId: cleanEnv(process.env.PINTEREST_CLIENT_ID),
  pinterestClientSecret: cleanEnv(process.env.PINTEREST_CLIENT_SECRET),
  pinterestCallbackUrl: cleanEnv(process.env.PINTEREST_CALLBACK_URL) || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/pinterest/callback`,
  pinterestScopes: process.env.PINTEREST_SCOPES || 'boards:read,pins:read,pins:write,user_accounts:read',
  pinterestContinuousRefresh: String(process.env.PINTEREST_CONTINUOUS_REFRESH || '').toLowerCase() === 'true',
  xClientId: cleanEnv(process.env.X_CLIENT_ID || process.env.TWITTER_CLIENT_ID),
  xClientSecret: cleanEnv(process.env.X_CLIENT_SECRET || process.env.TWITTER_CLIENT_SECRET),
  xCallbackUrl: cleanEnv(process.env.X_CALLBACK_URL || process.env.TWITTER_CALLBACK_URL) || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/x/callback`,
  xScopes: process.env.X_SCOPES || process.env.TWITTER_SCOPES || 'tweet.read tweet.write users.read offline.access',
  threadsAppId: cleanEnv(process.env.THREADS_APP_ID || process.env.THREADS_CLIENT_ID),
  threadsAppSecret: cleanEnv(process.env.THREADS_APP_SECRET || process.env.THREADS_CLIENT_SECRET),
  threadsCallbackUrl: cleanEnv(process.env.THREADS_CALLBACK_URL) || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/threads/callback`,
  threadsScopes: process.env.THREADS_SCOPES || 'threads_basic,threads_content_publish',
  threadsGraphVersion: process.env.THREADS_GRAPH_VERSION || 'v1.0',
  youtubeClientId: cleanEnv(process.env.YOUTUBE_CLIENT_ID || process.env.GOOGLE_CLIENT_ID),
  youtubeClientSecret: cleanEnv(process.env.YOUTUBE_CLIENT_SECRET || process.env.GOOGLE_CLIENT_SECRET),
  youtubeCallbackUrl: cleanEnv(process.env.YOUTUBE_CALLBACK_URL) || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/youtube/callback`,
  youtubeScopes: process.env.YOUTUBE_SCOPES || 'https://www.googleapis.com/auth/youtube.upload https://www.googleapis.com/auth/youtube.readonly',
  youtubeDefaultPrivacy: process.env.YOUTUBE_DEFAULT_PRIVACY || 'public',
  tiktokClientKey: cleanEnv(process.env.TIKTOK_CLIENT_KEY || process.env.TIKTOK_CLIENT_ID),
  tiktokClientSecret: cleanEnv(process.env.TIKTOK_CLIENT_SECRET),
  tiktokCallbackUrl: cleanEnv(process.env.TIKTOK_CALLBACK_URL) || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/tiktok/callback`,
  tiktokScopes: process.env.TIKTOK_SCOPES || 'user.info.basic,video.upload,video.publish',
  facebookAppId: process.env.FACEBOOK_APP_ID || '',
  facebookAppSecret: process.env.FACEBOOK_APP_SECRET || '',
  facebookCallbackUrl: process.env.FACEBOOK_CALLBACK_URL || `${process.env.APP_URL || 'http://localhost:3200'}/dashboard/actions/social/facebook/callback`,
  facebookGraphVersion: process.env.FACEBOOK_GRAPH_VERSION || 'v20.0',
  facebookScopes: process.env.FACEBOOK_SCOPES || 'pages_show_list,pages_manage_posts,pages_read_engagement',
  facebookLoginConfigId: process.env.FACEBOOK_LOGIN_CONFIG_ID || '',
  facebookAllowClassicOAuth: String(process.env.FACEBOOK_ALLOW_CLASSIC_OAUTH || '').toLowerCase() === 'true',
  facebookAppDomains: (process.env.FACEBOOK_APP_DOMAINS || '')
    .split(',')
    .map((domain) => domain.trim())
    .filter(Boolean),
  whatsappAccessToken: cleanEnv(process.env.WHATSAPP_ACCESS_TOKEN),
  whatsappPhoneNumberId: cleanEnv(process.env.WHATSAPP_PHONE_NUMBER_ID),
  whatsappBusinessAccountId: cleanEnv(process.env.WHATSAPP_BUSINESS_ACCOUNT_ID),
  whatsappDefaultRecipient: cleanEnv(process.env.WHATSAPP_DEFAULT_TO),
  redisHost: process.env.REDIS_HOST || '127.0.0.1',
  redisPort: Number(process.env.REDIS_PORT || 6379),
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET || 'change-this-access-secret',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || 'change-this-refresh-secret',
  jwtAccessExpiresIn: process.env.JWT_ACCESS_EXPIRES_IN || '5h',
  jwtRefreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || '5h',
  cookieSecret: process.env.COOKIE_SECRET || 'change-this-cookie-secret',
  csrfSecret: process.env.CSRF_SECRET || 'change-this-csrf-secret',
  webhookSecret: process.env.WEBHOOK_SECRET || ''
};

module.exports = env;
